name: Tests Dashboard

on:
  workflow_dispatch:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]
  schedule:
  - cron: "0 9 * * 1-5"

jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      
      - name: ⬇️ Checkout code # Downloads the repo into the runner.
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 📦 Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      # -------------------------
      # Get old history.json from gh-pages
      # -------------------------
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy old history.json if exists
        run: |
          mkdir -p dashboard
          if [ -f gh-pages/history.json ]; then
            cp gh-pages/history.json dashboard/history.json
          else
            echo "[]" > dashboard/history.json
          fi

      # -------------------------
      # Update history.json with latest run
      # -------------------------
      - name: Update history.json
        run: node dashboard/update-history.js

      # -------------------------
      # Prepare dashboard files
      # -------------------------
      - name: Copy dashboard files
        run: |
          mkdir -p public
          cp dashboard/history.json public/
          cp playwright-report/test-results.json public/
          cp dashboard/index.html public/
          cp dashboard/styles.css public/
          cp dashboard/script.js public/

      # -------------------------
      # Deploy to GitHub Pages
      # -------------------------
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

     # - name: Copy JSON report to dashboard folder
     #  run: cp playwright-report/test-results.json dashboard/test-results.json

      #- name: 📊 Upload test report as artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: test-report
      #   path: playwright-report/

      #- name: 🌐 Deploy dashboard to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GH_PAT }}
      #    publish_dir: ./dashboard
      #    publish_branch: gh-pages
