name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 9 * * 1-5"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      # Downloads the repo into the runner.
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 📦 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 📂 Prepare folders to store newman report
        run: mkdir -p playwright-report
        
      - name: ▶️ Run Playwright tests
        run: |
          mkdir -p playwright-report
          npx playwright test --reporter=json --output=playwright-report
        continue-on-error: true

      - name: 📊 Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: playwright-report/

      - name: ➡️ Checkout gh-pages branch (create if missing)
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
          fi
      
      - name: 📚 Get previous reports from gh-pages branch
        run: |
          if git ls-remote --exit-code origin gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
            rsync -a --ignore-missing-args ./ ./playwright-report || true
            git checkout -
          else
            echo "No gh-pages branch found. Skipping report retrieval."
          fi

      - name: 🗄 Create folder for current report
        run: |
          export TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          mkdir -p "report/$TIMESTAMP"
          cp -R playwright-report/ "reports/$TIMESTAMP" # Copy files of new report
          echo "Report generated in: report/$TIMESTAMP"

      - name: 📝 Generate reports hub page (index.html)
      # Create page to list all the generated reports
        run: |
          cat << 'EOF' > playwright-report/index.html
          <!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Test Reports</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <style>
              body { margin: 20px; }
              h1 { margin-bottom: 20px; }
              ul { list-style-type: none; padding: 0; }
              li { margin-bottom: 10px; }
              a { text-decoration: none; color: #0d6efd; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1 class="display-4">Test Reports</h1>
              <ul>
          EOF
            for dir in playwright-report/*/ ; do
              [ -d "$dir" ] || continue
              dirname=$(basename "$dir")
              if [ "$dirname" != "index.html" ]; then
                echo "<li><a href=\"${dirname}/report.html\">${dirname}</a></li>" >> playwright-report/index.html # List links to generate reports in reports hub (index.html)
              fi
            done
          cat << 'EOF' >> pages/index.html
              </ul>
            </div>
          </body>
          </html>
          EOF

      - name: 🌐 Publish reports in GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./playwright-report
          enable_jekyll: false
